main:
  - name: About
    url: /
    weight: 10
  - name: Publications
    url: /publications/
    weight: 20
  - name: Projects
    url: /projects/
    weight: 30
  - name: Experience
    url: /experience/
    weight: 40
